#!/usr/bin/env bash
# T09 / ADR-001: annotated, runnable example of the graphs T11 must generate (render by blocks + concat).
# Plan (1920x1080, 30 fps, gap 8 px, transition fade 0.5 s), 4 s:
#   column 0: v-1080x1920-12s.mp4 [0, 4)       width 632 → 776 (vertical clip: the crop becomes width-limited → zoom)
#   column 1: h-1080p-10s.mp4     [0, 2.5)     width 1280 → 1136
#             h-720p-25fps-8s.mp4 [2, 4)       replaces it with an xfade (25 fps source → 30 fps)
#   layout keyframe at t=2 with transitionDuration 0.5: the re-layout and the xfade happen at the same time.
# Blocks: [0,2) stable · [2,2.5) animation · [2.5,4) stable. Generated by `renderSpike.ts example` (then annotated).
# Run from the repo root: bash script/videomix/spike/example-anim-chunk.sh
set -euo pipefail
FF=${FFMPEG_PATH:-ffmpeg/linux-x64/lib/ffmpeg}
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:-ffmpeg/linux-x64/lib}
OUT=test-media/spike-out/example-sh
mkdir -p "$OUT"
join() { local IFS=';'; echo "$*"; }
ENC=(-c:v libx264 -preset medium -crf 20 -pix_fmt yuv420p -r 30 -an)

# ---- Block 0: [0, 2) s, stable layout → static path (crop + scale to the exact column size) -------------------------
G0=(
  # Per clip: fps first (no setpts=PTS-STARTPTS before fps: after -ss the first frame may not be at 0 and resetting it
  # shifts the clip by up to one source frame), clone-pad against short sources, exact frame count, then crop from
  # geometry.getCropForAspect(max, min, w/H) and scale to the column size.
  # When the seek point is > 0 (blocks 1 and 2) the input is opened 0.1 s earlier (-ss seek-0.1) and shifted back with
  # setpts=PTS-0.1/TB: ffmpeg's accurate seek drops the source frame still on screen at the seek point, and without the
  # preroll the first output frame of the block would show the next source frame (seen with 25 fps sources).
  "[0:v]fps=30:start_time=0,tpad=stop_mode=clone:stop_duration=1,trim=end_frame=60,setpts=PTS-STARTPTS,crop=1080:1846:0:38,scale=632:1080:flags=bicubic,setsar=1[c0]"
  "[1:v]fps=30:start_time=0,tpad=stop_mode=clone:stop_duration=1,trim=end_frame=60,setpts=PTS-STARTPTS,crop=1280:1080:320:0,scale=1280:1080:flags=bicubic,setsar=1[c1]"
  # Canvas = gap colour; columns overlaid at their x (the gap is simply the canvas showing through)
  "color=c=0x303030:s=1920x1080:r=30:d=2,format=yuv420p[cv0]"
  "[cv0][c0]overlay=x=0:y=0:eof_action=pass[cv1]"
  "[cv1][c1]overlay=x=640:y=0:eof_action=pass,format=yuv420p[vout]"
)
"$FF" -hide_banner -y -loglevel error \
  -ss 0 -t 2.5 -i test-media/v-1080x1920-12s.mp4 \
  -ss 0 -t 2.5 -i test-media/h-1080p-10s.mp4 \
  -filter_complex "$(join "${G0[@]}")" -map '[vout]' -frames:v 60 "${ENC[@]}" "$OUT/chunk-000.mp4"

# ---- Block 1: [2, 2.5) s, animated re-layout (+ xfade in column 1) → "column layer" path -----------------------------
# Every value below is sampled once per output frame by T11 (geometry.ts per frame, widths eased with smoothstep) and
# written as a flat sum of steps  v0 + Δ1·gte(t,T1) + …  (T = (m − 0.5)/fps). Nested if() is NOT usable: ffmpeg rejects
# expressions nested deeper than ~98 levels.
VW='632+2*gte(t,0.0167)+4*gte(t,0.05)+8*gte(t,0.0833)+12*gte(t,0.1167)+12*gte(t,0.15)+12*gte(t,0.1833)+14*gte(t,0.2167)+16*gte(t,0.25)+14*gte(t,0.2833)+12*gte(t,0.3167)+12*gte(t,0.35)+12*gte(t,0.3833)+8*gte(t,0.4167)+4*gte(t,0.45)'
VH='1082+2*gte(t,0.0167)+10*gte(t,0.05)+14*gte(t,0.0833)+16*gte(t,0.1167)+22*gte(t,0.15)+22*gte(t,0.1833)+24*gte(t,0.2167)+24*gte(t,0.25)+26*gte(t,0.2833)+22*gte(t,0.3167)+20*gte(t,0.35)+18*gte(t,0.3833)+14*gte(t,0.4167)+8*gte(t,0.45)'
VY='-1-1*gte(t,0.0167)-5*gte(t,0.05)-7*gte(t,0.0833)-8*gte(t,0.1167)-11*gte(t,0.15)-11*gte(t,0.1833)-12*gte(t,0.2167)-12*gte(t,0.25)-13*gte(t,0.2833)-11*gte(t,0.3167)-10*gte(t,0.35)-9*gte(t,0.3833)-7*gte(t,0.4167)-4*gte(t,0.45)'
GX='0-1*gte(t,0.0167)-2*gte(t,0.05)-4*gte(t,0.0833)-6*gte(t,0.1167)-6*gte(t,0.15)-6*gte(t,0.1833)-7*gte(t,0.2167)-8*gte(t,0.25)-7*gte(t,0.2833)-6*gte(t,0.3167)-6*gte(t,0.35)-6*gte(t,0.3833)-4*gte(t,0.4167)-2*gte(t,0.45)'
FX='-2-1*gte(t,0.0167)-2*gte(t,0.05)-4*gte(t,0.0833)-6*gte(t,0.1167)-6*gte(t,0.15)-6*gte(t,0.1833)-7*gte(t,0.2167)-8*gte(t,0.25)-7*gte(t,0.2833)-6*gte(t,0.3167)-6*gte(t,0.35)-6*gte(t,0.3833)-4*gte(t,0.4167)-2*gte(t,0.45)'
C1X='640+2*gte(t,0.0167)+4*gte(t,0.05)+8*gte(t,0.0833)+12*gte(t,0.1167)+12*gte(t,0.15)+12*gte(t,0.1833)+14*gte(t,0.2167)+16*gte(t,0.25)+14*gte(t,0.2833)+12*gte(t,0.3167)+12*gte(t,0.35)+12*gte(t,0.3833)+8*gte(t,0.4167)+4*gte(t,0.45)'
GAPX=$VW # right edge of column 0 (x0 + w0(t)); here x0 = 0
G1=(
  # Column 0 (vertical clip, zooms): crop ONCE the union U of all per-frame crops, then scale U per frame
  # (scale eval=frame emits frames of varying size) so that the per-frame crop C(t) gets height H...
  "[0:v]setpts=PTS-0.1/TB,fps=30:start_time=0,tpad=stop_mode=clone:stop_duration=1,trim=end_frame=15,setpts=PTS-STARTPTS,crop=1080:1848:0:36,scale=w='$VW':h='$VH':eval=frame:flags=bicubic,setsar=1[sc0]"
  # ...and place it with overlay (which accepts variable-size overlay frames) on a FIXED-size base as wide as the
  # widest state of the column (776). Offsets = centre C(t) in the window [0, w(t)) of the layer ("left-anchored").
  # For pillarbox/letterbox states the base is the blurred cover of the clip instead of black.
  "color=c=black:s=776x1080:r=30:d=0.5[base0]"
  "[base0][sc0]overlay=x=0:y='$VY':eval=frame:shortest=1[col0]"
  # Column 1, outgoing clip (no zoom: the scale is constant, only the offset moves to keep it centred)
  "[1:v]setpts=PTS-0.1/TB,fps=30:start_time=0,tpad=stop_mode=clone:stop_duration=1,trim=end_frame=15,setpts=PTS-STARTPTS,crop=1280:1080:320:0,scale=1280:1080,setsar=1[sc1]"
  "color=c=black:s=1282x1080:r=30:d=0.5[base1]"
  "[base1][sc1]overlay=x='$GX':y=0:eval=frame:shortest=1[l1]"
  # Column 1, incoming clip (25 fps source → fps=30), same layer size → xfade works (xfade needs equal fixed sizes)
  "[2:v]fps=30:start_time=0,tpad=stop_mode=clone:stop_duration=1,trim=end_frame=15,setpts=PTS-STARTPTS,crop=856:720:212:0,scale=1284:1080,setsar=1[sc2]"
  "color=c=black:s=1282x1080:r=30:d=0.5[base2]"
  "[base2][sc2]overlay=x='$FX':y=0:eval=frame:shortest=1[l2]"
  "[l1][l2]xfade=transition=fade:duration=0.5:offset=0[col1]"
  # Canvas: layers overlaid LEFT → RIGHT at x(t). Each layer is wider than its window; the part to the right of the
  # window is hidden by the next column (stacking order). Then the gap bars are redrawn on top at x0 + w0(t).
  "color=c=0x303030:s=1920x1080:r=30:d=0.5,format=yuv420p[cv0]"
  "[cv0][col0]overlay=x=0:y=0:eof_action=pass[cv1]"
  "[cv1][col1]overlay=x='$C1X':y=0:eval=frame:eof_action=pass[cv2]"
  "color=c=0x303030:s=8x1080:r=30:d=0.5[gap0]"
  "[cv2][gap0]overlay=x='$GAPX':y=0:eval=frame,format=yuv420p[vout]"
)
"$FF" -hide_banner -y -loglevel error \
  -ss 1.9 -t 1.1 -i test-media/v-1080x1920-12s.mp4 \
  -ss 1.9 -t 1.1 -i test-media/h-1080p-10s.mp4 \
  -ss 0 -t 1 -i test-media/h-720p-25fps-8s.mp4 \
  -filter_complex "$(join "${G1[@]}")" -map '[vout]' -frames:v 15 "${ENC[@]}" "$OUT/chunk-001.mp4"

# ---- Block 2: [2.5, 4) s, stable again (new widths) ----------------------------------------------------------------
G2=(
  "[0:v]setpts=PTS-0.1/TB,fps=30:start_time=0,tpad=stop_mode=clone:stop_duration=1,trim=end_frame=45,setpts=PTS-STARTPTS,crop=1080:1504:0:208,scale=776:1080:flags=bicubic,setsar=1[c0]"
  "[1:v]setpts=PTS-0.1/TB,fps=30:start_time=0,tpad=stop_mode=clone:stop_duration=1,trim=end_frame=45,setpts=PTS-STARTPTS,crop=758:720:262:0,scale=1136:1080:flags=bicubic,setsar=1[c1]"
  "color=c=0x303030:s=1920x1080:r=30:d=1.5,format=yuv420p[cv0]"
  "[cv0][c0]overlay=x=0:y=0:eof_action=pass[cv1]"
  "[cv1][c1]overlay=x=784:y=0:eof_action=pass,format=yuv420p[vout]"
)
"$FF" -hide_banner -y -loglevel error \
  -ss 2.4 -t 2.1 -i test-media/v-1080x1920-12s.mp4 \
  -ss 0.4 -t 2.1 -i test-media/h-720p-25fps-8s.mp4 \
  -filter_complex "$(join "${G2[@]}")" -map '[vout]' -frames:v 45 "${ENC[@]}" "$OUT/chunk-002.mp4"

# ---- Audio: ONE pass over the whole duration (-vn as input option: video is not decoded) ---------------------------
# per clip: format → gain (loudness + gainDb, T12) → afade in/out of D (not at the video edges) → adelay to startTime;
# amix normalize=0; compensation −10·log10(n) dB with D-long ramps (here n=2 all the time → ×0.7071); limiter.
A=(
  "[0:a]asetpts=PTS-STARTPTS,aresample=48000,aformat=sample_fmts=fltp:channel_layouts=stereo,atrim=duration=4,volume=0dB[a0]"
  "[1:a]asetpts=PTS-STARTPTS,aresample=48000,aformat=sample_fmts=fltp:channel_layouts=stereo,atrim=duration=2.5,volume=0dB,afade=t=out:st=2:d=0.5[a1]"
  "[2:a]asetpts=PTS-STARTPTS,aresample=48000,aformat=sample_fmts=fltp:channel_layouts=stereo,atrim=duration=2,volume=0dB,afade=t=in:d=0.5,adelay=2000:all=1[a2]"
  "[a0][a1][a2]amix=inputs=3:normalize=0:duration=longest,volume=0.7071[mix]"
  # music: -stream_loop -1 on the input, cut to the duration, own volume, final fade-out of max(2 s, D)
  "[3:a]aresample=48000,aformat=sample_fmts=fltp:channel_layouts=stereo,atrim=duration=4,volume=-12dB,afade=t=out:st=2:d=2[music]"
  "[mix][music]amix=inputs=2:normalize=0:duration=first,atrim=duration=4,alimiter=limit=0.95:level=disabled[aout]"
)
"$FF" -hide_banner -y -loglevel error \
  -vn -ss 0 -t 4.1 -i test-media/v-1080x1920-12s.mp4 \
  -vn -ss 0 -t 2.6 -i test-media/h-1080p-10s.mp4 \
  -vn -ss 0 -t 2.1 -i test-media/h-720p-25fps-8s.mp4 \
  -stream_loop -1 -i test-media/music-20s.m4a \
  -filter_complex "$(join "${A[@]}")" -map '[aout]' -c:a aac -b:a 192k -ar 48000 "$OUT/audio.m4a"

# ---- Join: concat demuxer without re-encoding + mux the audio ------------------------------------------------------
printf "file 'chunk-%03d.mp4'\n" 0 1 2 > "$OUT/list.txt"
"$FF" -hide_banner -y -loglevel error -f concat -safe 0 -i "$OUT/list.txt" -i "$OUT/audio.m4a" \
  -map 0:v -map 1:a -c copy -movflags +faststart "$OUT/example.mp4"
echo "written $OUT/example.mp4"
