import isEqual from 'lodash/isEqual';

import type { LoudnessMeasurement, MixClip, MixMusicPlaylist, MixMusicTrack, MixOverlay, MixProject, MixSettings, MixSource } from './types';
import { getOutputSize } from './types';
import { detachOverlayReferences } from './overlays/anchors';
import type { OverlayTimeRange } from './overlays/anchors';
import { isVisualOverlay } from './overlays/factories';
import { refitImageOverlayBox } from './overlayTimeline';
import type { Size } from './overlayMath';
import { normalizeSar } from './sampleAspect';
import { getSourceFrameChange, rescaleClipRects } from './sourceResize';

/** Fields of a clip that can be edited after creation. */
export type MixClipPatch = Partial<Omit<MixClip, 'id' | 'sourceId'>>;

/** Fields updated when a missing source is located again (or its cached probe info refreshed). */
export type MixSourceRelink = Pick<MixSource, 'path' | 'absolutePath'> & Partial<Pick<MixSource, 'name' | 'width' | 'height' | 'duration' | 'sar'>>;

/** Editable fields of an overlay (of its own type: the reducer doesn't check that the patch matches it). */
export type MixOverlayPatch = { [T in MixOverlay as T['type']]: Partial<Omit<T, 'id' | 'type'>> }[MixOverlay['type']];

/** Editable fields of a music track. */
export type MixMusicTrackPatch = Partial<Omit<MixMusicTrack, 'id'>>;

/** Playlist fields other than the tracks (which have their own actions). */
export type MixMusicPlaylistPatch = Partial<Omit<MixMusicPlaylist, 'tracks'>>;

/** Layer moves. Visual overlays move past the next/previous visual overlay (sounds aren't layered), sounds past sounds. */
export type OverlayLayerMove = 'up' | 'down' | 'front' | 'back';

/**
 * Times resolved (resolveOverlayTimes) before removing a clip/overlay/source: the overlays anchored to it become absolute
 * at their current start (see detachOverlayReferences). Without it they fall back to `max(0, offset)`.
 */
export type ResolvedOverlayTimesForRemoval = ReadonlyMap<string, OverlayTimeRange> | undefined;

/**
 * Edits of a {@link MixProject}. Ids are generated by the caller, so the reducer stays pure and deterministic.
 * An action that changes nothing returns the same project object (the history uses this to skip no-op steps).
 */
export type MixProjectAction =
  | { type: 'addSources', sources: MixSource[] }
  /** Also removes the clips of the source (the UI warns before). */
  | { type: 'removeSource', sourceId: string, resolved?: ResolvedOverlayTimesForRemoval }
  | { type: 'relinkSource', sourceId: string, source: MixSourceRelink }
  /** Inserted at `index`, or appended. */
  | { type: 'addClip', clip: MixClip, index?: number | undefined }
  | { type: 'updateClip', clipId: string, patch: MixClipPatch }
  | { type: 'removeClip', clipId: string, resolved?: ResolvedOverlayTimesForRemoval }
  /** The copy is inserted right after the original. */
  | { type: 'duplicateClip', clipId: string, newId: string, name?: string | undefined }
  /** New list order. Ids not listed keep their relative order at the end; unknown ids are ignored. */
  | { type: 'reorderClips', ids: string[] }
  /** Pins the clip at a time of the final video (A4), or unpins it (`undefined`). */
  | { type: 'setClipPinTime', clipId: string, pinTime: number | undefined }
  /**
   * The clips (at least 2 existing ones, else nothing happens) start together (A4). They leave their previous groups;
   * a group left with a single clip is dissolved.
   */
  | { type: 'groupClips', clipIds: string[], groupId: string }
  /** The clips leave their groups; a group left with a single clip is dissolved. */
  | { type: 'ungroupClips', clipIds: string[] }
  /** Manual exception over the automatic link with the previous clip of its source (E2, T36), or clears it (`undefined`). */
  | { type: 'setClipLink', clipId: string, link: MixClip['link'] }
  /** Replaces the always-visible sequence (E5, T36). Ids not in the project are dropped. */
  | { type: 'setAlwaysVisibleClips', clipIds: string[] }
  /**
   * `imageSizes` (T34, pending from T29): pixel size of each image overlay whose file could be read, keyed by overlay id.
   * When `patch.output` changes the aspect, the boxes of the image overlays present in this map are refit to keep the
   * image's proportion on the new frame, centered on their previous box (see `refitImageOverlayBox`); overlays missing
   * from the map (their file couldn't be read) keep their box unchanged.
   */
  | { type: 'updateSettings', patch: Partial<MixSettings>, imageSizes?: ReadonlyMap<string, Size> }
  /** Music playlist (C2). Inserted at `index`, or appended. */
  | { type: 'addMusicTracks', tracks: MixMusicTrack[], index?: number | undefined }
  | { type: 'updateMusicTrack', trackId: string, patch: MixMusicTrackPatch }
  | { type: 'removeMusicTrack', trackId: string }
  /** New play order. Ids not listed keep their relative order at the end; unknown ids are ignored. */
  | { type: 'reorderMusicTracks', ids: string[] }
  | { type: 'updateMusicPlaylist', patch: MixMusicPlaylistPatch }
  | { type: 'setLoudnessCache', loudnessCache: Record<string, LoudnessMeasurement> | undefined }
  /** Inserted at `index` (layer order), or appended (on top). */
  | { type: 'addOverlay', overlay: MixOverlay, index?: number | undefined }
  | { type: 'updateOverlay', overlayId: string, patch: MixOverlayPatch }
  /** Overlays anchored to it become absolute, bars linked to it are unlinked. */
  | { type: 'removeOverlay', overlayId: string, resolved?: ResolvedOverlayTimesForRemoval }
  /** The copy is inserted right after the original (one layer above). Dependents aren't duplicated. */
  | { type: 'duplicateOverlay', overlayId: string, newId: string, name?: string | undefined }
  | { type: 'moveOverlayLayer', overlayId: string, to: OverlayLayerMove }
  /** Several edits applied in order as one undo step (e.g. the changes made in the timeline, or splitting a clip). */
  | { type: 'batch', actions: MixProjectAction[] };

// Optional keys are removed instead of being stored as `undefined`, so saved files and deep comparisons stay clean.
function withoutUndefined<T extends object>(obj: T, keys: (keyof T & string)[]): T {
  return Object.fromEntries(Object.entries(obj).filter(([key, value]) => value !== undefined || !(keys as string[]).includes(key))) as T;
}

const hasChanges = <T extends object>(obj: T, patch: Partial<T>) => (Object.keys(patch) as (keyof T)[]).some((key) => !isEqual(obj[key], patch[key]));

/** `items` in the order of `ids` (unknown ids ignored), then the rest in their order. The same array if nothing moves. */
function reorderById<T extends { id: string }>(items: T[], ids: string[]): T[] {
  const byId = new Map(items.map((item) => [item.id, item]));
  const listed = new Set<string>();
  const ordered: T[] = [];
  ids.forEach((id) => {
    const item = byId.get(id);
    if (item == null || listed.has(id)) return;
    listed.add(id);
    ordered.push(item);
  });
  const ret = [...ordered, ...items.filter((item) => !listed.has(item.id))];
  return ret.every((item, i) => item === items[i]) ? items : ret;
}

/** Removes `groupId` from the clips whose group has a single clip (A4: a group needs 2). The same array if none. */
export function dissolveSingleClipGroups(clips: MixClip[]): MixClip[] {
  const counts = new Map<string, number>();
  clips.forEach(({ groupId }) => {
    if (groupId != null) counts.set(groupId, (counts.get(groupId) ?? 0) + 1);
  });
  if (![...counts.values()].includes(1)) return clips;
  return clips.map((clip) => (clip.groupId != null && counts.get(clip.groupId) === 1 ? withoutUndefined({ ...clip, groupId: undefined }, ['groupId']) : clip));
}

const clipOptionalKeys: (keyof MixClip)[] = ['minRect', 'pinTime', 'groupId', 'link'];

function updateMusicPlaylist(project: MixProject, musicPlaylist: MixMusicPlaylist): MixProject {
  return { ...project, settings: { ...project.settings, musicPlaylist } };
}

/** Drops ids no longer in `clipIds` from the always-visible sequence (E5), e.g. after removing a clip/source. Same array if none. */
function pruneAlwaysVisible(clipIds: ReadonlySet<string>, sequence: string[]): string[] {
  const pruned = sequence.filter((id) => clipIds.has(id));
  return pruned.length === sequence.length ? sequence : pruned;
}

export function mixProjectReducer(project: MixProject, action: MixProjectAction): MixProject {
  switch (action.type) {
    case 'addSources': {
      // The same file can only be a source once
      const existing = new Set(project.sources.map((s) => s.absolutePath));
      const newSources = action.sources.filter((s) => {
        if (existing.has(s.absolutePath) || project.sources.some((s2) => s2.id === s.id)) return false;
        existing.add(s.absolutePath);
        return true;
      });
      if (newSources.length === 0) return project;
      return { ...project, sources: [...project.sources, ...newSources] };
    }

    case 'removeSource': {
      if (!project.sources.some((s) => s.id === action.sourceId)) return project;
      const clipIds = new Set(project.clips.filter((c) => c.sourceId === action.sourceId).map((c) => c.id));
      const clips = dissolveSingleClipGroups(project.clips.filter((c) => c.sourceId !== action.sourceId));
      const { alwaysVisible } = project.settings;
      const prunedAlwaysVisible = pruneAlwaysVisible(new Set(clips.map((c) => c.id)), alwaysVisible.clipIds);
      return {
        ...project,
        sources: project.sources.filter((s) => s.id !== action.sourceId),
        clips,
        ...(prunedAlwaysVisible !== alwaysVisible.clipIds && { settings: { ...project.settings, alwaysVisible: { clipIds: prunedAlwaysVisible } } }),
        overlays: detachOverlayReferences(project.overlays, { clipIds, resolved: action.resolved }),
      };
    }

    case 'relinkSource': {
      const index = project.sources.findIndex((s) => s.id === action.sourceId);
      const source = project.sources[index];
      // B1: square pixels are stored as no SAR
      const patch = 'sar' in action.source ? { ...action.source, sar: normalizeSar(action.source.sar) } : action.source;
      if (source == null || !hasChanges(source, patch)) return project;
      const sources = [...project.sources];
      sources[index] = withoutUndefined({ ...source, ...patch }, ['width', 'height', 'duration', 'sar']);
      // B2: a new frame size scales the rects of the source's clips
      const change = getSourceFrameChange(source, patch);
      if (change == null) return { ...project, sources };
      const clips = project.clips.map((c) => (c.sourceId === source.id ? withoutUndefined({ ...c, ...rescaleClipRects(c, change) }, clipOptionalKeys) : c));
      return { ...project, sources, clips };
    }

    case 'addClip': {
      if (project.clips.some((c) => c.id === action.clip.id)) throw new Error(`Duplicate clip id ${action.clip.id}`);
      const clips = [...project.clips];
      clips.splice(action.index ?? clips.length, 0, action.clip);
      return { ...project, clips };
    }

    case 'updateClip': {
      const index = project.clips.findIndex((c) => c.id === action.clipId);
      const clip = project.clips[index];
      if (clip == null || !hasChanges(clip, action.patch)) return project;
      const clips = [...project.clips];
      clips[index] = withoutUndefined({ ...clip, ...action.patch }, clipOptionalKeys);
      return { ...project, clips };
    }

    case 'removeClip': {
      if (!project.clips.some((c) => c.id === action.clipId)) return project;
      const clips = dissolveSingleClipGroups(project.clips.filter((c) => c.id !== action.clipId));
      const { alwaysVisible } = project.settings;
      const prunedAlwaysVisible = pruneAlwaysVisible(new Set(clips.map((c) => c.id)), alwaysVisible.clipIds);
      return {
        ...project,
        clips,
        ...(prunedAlwaysVisible !== alwaysVisible.clipIds && { settings: { ...project.settings, alwaysVisible: { clipIds: prunedAlwaysVisible } } }),
        overlays: detachOverlayReferences(project.overlays, { clipIds: new Set([action.clipId]), resolved: action.resolved }),
      };
    }

    case 'duplicateClip': {
      const index = project.clips.findIndex((c) => c.id === action.clipId);
      const clip = project.clips[index];
      if (clip == null) return project;
      if (project.clips.some((c) => c.id === action.newId)) throw new Error(`Duplicate clip id ${action.newId}`);
      const clips = [...project.clips];
      // The copy is neither pinned nor grouped (it would start at the same time as the original), and has no link
      // exception of its own (T36): it's a new, unrelated clip until the user re-times it.
      const copy = { ...structuredClone(clip), id: action.newId, name: action.name ?? clip.name, pinTime: undefined, groupId: undefined, link: undefined };
      clips.splice(index + 1, 0, withoutUndefined(copy, ['pinTime', 'groupId', 'link']));
      return { ...project, clips };
    }

    case 'reorderClips': {
      const clips = reorderById(project.clips, action.ids);
      return clips === project.clips ? project : { ...project, clips };
    }

    case 'setClipPinTime': {
      return mixProjectReducer(project, { type: 'updateClip', clipId: action.clipId, patch: { pinTime: action.pinTime } });
    }

    case 'groupClips': {
      const ids = new Set(action.clipIds);
      if (project.clips.filter((c) => ids.has(c.id)).length < 2) return project;
      const clips = dissolveSingleClipGroups(project.clips.map((c) => (ids.has(c.id) && c.groupId !== action.groupId ? { ...c, groupId: action.groupId } : c)));
      return clips.every((c, i) => c === project.clips[i]) ? project : { ...project, clips };
    }

    case 'ungroupClips': {
      const ids = new Set(action.clipIds);
      const clips = dissolveSingleClipGroups(project.clips.map((c) => (ids.has(c.id) && c.groupId != null ? withoutUndefined({ ...c, groupId: undefined }, ['groupId']) : c)));
      return clips.every((c, i) => c === project.clips[i]) ? project : { ...project, clips };
    }

    case 'setClipLink': {
      return mixProjectReducer(project, { type: 'updateClip', clipId: action.clipId, patch: { link: action.link } });
    }

    case 'setAlwaysVisibleClips': {
      const { alwaysVisible } = project.settings;
      const knownIds = new Set(project.clips.map((c) => c.id));
      // Drops duplicates and unknown ids (kept, deduplicated, in the given order)
      const clipIds = [...new Set(action.clipIds.filter((id) => knownIds.has(id)))];
      if (isEqual(clipIds, alwaysVisible.clipIds)) return project;
      return { ...project, settings: { ...project.settings, alwaysVisible: { clipIds } } };
    }

    case 'updateSettings': {
      if (!hasChanges(project.settings, action.patch)) return project;
      const settings = { ...project.settings, ...action.patch };
      // Pending from T29: refit image overlays to the new frame's proportion when the output aspect changes
      const aspectChanged = action.patch.output != null && action.patch.output.aspect !== project.settings.output.aspect;
      if (!aspectChanged || action.imageSizes == null || action.imageSizes.size === 0) return { ...project, settings };
      const frame = getOutputSize(settings.output);
      const overlays = project.overlays.map((overlay) => {
        if (overlay.type !== 'image') return overlay;
        const imageSize = action.imageSizes?.get(overlay.id);
        if (imageSize == null) return overlay;
        return { ...overlay, box: refitImageOverlayBox(overlay.box, imageSize, frame) };
      });
      return { ...project, settings, overlays };
    }

    case 'addMusicTracks': {
      const { musicPlaylist } = project.settings;
      if (action.tracks.length === 0) return project;
      const ids = new Set(musicPlaylist.tracks.map((t) => t.id));
      action.tracks.forEach(({ id }) => {
        if (ids.has(id)) throw new Error(`Duplicate music track id ${id}`);
        ids.add(id);
      });
      const tracks = [...musicPlaylist.tracks];
      tracks.splice(action.index ?? tracks.length, 0, ...action.tracks);
      return updateMusicPlaylist(project, { ...musicPlaylist, tracks });
    }

    case 'updateMusicTrack': {
      const { musicPlaylist } = project.settings;
      const index = musicPlaylist.tracks.findIndex((t) => t.id === action.trackId);
      const track = musicPlaylist.tracks[index];
      if (track == null || !hasChanges(track, action.patch)) return project;
      const tracks = [...musicPlaylist.tracks];
      tracks[index] = { ...track, ...action.patch };
      return updateMusicPlaylist(project, { ...musicPlaylist, tracks });
    }

    case 'removeMusicTrack': {
      const { musicPlaylist } = project.settings;
      if (!musicPlaylist.tracks.some((t) => t.id === action.trackId)) return project;
      return updateMusicPlaylist(project, { ...musicPlaylist, tracks: musicPlaylist.tracks.filter((t) => t.id !== action.trackId) });
    }

    case 'reorderMusicTracks': {
      const { musicPlaylist } = project.settings;
      const tracks = reorderById(musicPlaylist.tracks, action.ids);
      return tracks === musicPlaylist.tracks ? project : updateMusicPlaylist(project, { ...musicPlaylist, tracks });
    }

    case 'updateMusicPlaylist': {
      const { musicPlaylist } = project.settings;
      if (!hasChanges(musicPlaylist, action.patch)) return project;
      return updateMusicPlaylist(project, { ...musicPlaylist, ...action.patch });
    }

    case 'setLoudnessCache': {
      if (project.loudnessCache === action.loudnessCache) return project;
      return withoutUndefined({ ...project, loudnessCache: action.loudnessCache }, ['loudnessCache']);
    }

    case 'addOverlay': {
      if (project.overlays.some((o) => o.id === action.overlay.id)) throw new Error(`Duplicate overlay id ${action.overlay.id}`);
      const overlays = [...project.overlays];
      overlays.splice(action.index ?? overlays.length, 0, action.overlay);
      return { ...project, overlays };
    }

    case 'updateOverlay': {
      const index = project.overlays.findIndex((o) => o.id === action.overlayId);
      const overlay = project.overlays[index];
      if (overlay == null || !hasChanges<Record<string, unknown>>(overlay, action.patch)) return project;
      const overlays = [...project.overlays];
      overlays[index] = withoutUndefined<Record<string, unknown>>({ ...overlay, ...action.patch }, ['font', 'shadow', 'linkedCountdownId']) as MixOverlay;
      return { ...project, overlays };
    }

    case 'removeOverlay': {
      if (!project.overlays.some((o) => o.id === action.overlayId)) return project;
      const overlays = project.overlays.filter((o) => o.id !== action.overlayId);
      return { ...project, overlays: detachOverlayReferences(overlays, { overlayIds: new Set([action.overlayId]), resolved: action.resolved }) };
    }

    case 'duplicateOverlay': {
      const index = project.overlays.findIndex((o) => o.id === action.overlayId);
      const overlay = project.overlays[index];
      if (overlay == null) return project;
      if (project.overlays.some((o) => o.id === action.newId)) throw new Error(`Duplicate overlay id ${action.newId}`);
      const overlays = [...project.overlays];
      overlays.splice(index + 1, 0, { ...structuredClone(overlay), id: action.newId, name: action.name ?? overlay.name });
      return { ...project, overlays };
    }

    case 'moveOverlayLayer': {
      const index = project.overlays.findIndex((o) => o.id === action.overlayId);
      const overlay = project.overlays[index];
      if (overlay == null) return project;
      const visual = isVisualOverlay(overlay);
      // Indexes of the overlays of the same group (visual or sound), in layer order
      const group = project.overlays.flatMap((o, i) => (isVisualOverlay(o) === visual ? [i] : []));
      const pos = group.indexOf(index);
      const targetPos = { up: pos + 1, down: pos - 1, front: group.length - 1, back: 0 }[action.to];
      const target = group[targetPos];
      if (target == null || target === index) return project;
      const overlays = [...project.overlays];
      overlays.splice(index, 1);
      overlays.splice(target, 0, overlay);
      return { ...project, overlays };
    }

    case 'batch': {
      return action.actions.reduce((acc, a) => mixProjectReducer(acc, a), project);
    }

    default: {
      const exhaustive: never = action;
      throw new Error(`Unknown action ${JSON.stringify(exhaustive)}`);
    }
  }
}

/** A new source for a media file. `filePath` must be absolute (it's also the fallback path). */
export function createMixSource({ id, filePath, name }: { id: string, filePath: string, name: string }): MixSource {
  return { id, path: filePath, absolutePath: filePath, name };
}
