import isEqual from 'lodash/isEqual';

import type { LoudnessMeasurement, MixClip, MixProject, MixSettings, MixSource } from './types';

/** Fields of a clip that can be edited after creation. */
export type MixClipPatch = Partial<Omit<MixClip, 'id' | 'sourceId'>>;

/** Fields updated when a missing source is located again (or its cached probe info refreshed). */
export type MixSourceRelink = Pick<MixSource, 'path' | 'absolutePath'> & Partial<Pick<MixSource, 'name' | 'width' | 'height' | 'duration'>>;

/**
 * Edits of a {@link MixProject}. Ids are generated by the caller, so the reducer stays pure and deterministic.
 * An action that changes nothing returns the same project object (the history uses this to skip no-op steps).
 */
export type MixProjectAction =
  | { type: 'addSources', sources: MixSource[] }
  /** Also removes the clips of the source (the UI warns before). */
  | { type: 'removeSource', sourceId: string }
  | { type: 'relinkSource', sourceId: string, source: MixSourceRelink }
  /** Inserted at `index`, or appended. */
  | { type: 'addClip', clip: MixClip, index?: number | undefined }
  | { type: 'updateClip', clipId: string, patch: MixClipPatch }
  | { type: 'removeClip', clipId: string }
  /** The copy is inserted right after the original. */
  | { type: 'duplicateClip', clipId: string, newId: string, name?: string | undefined }
  /** New list order. Ids not listed keep their relative order at the end; unknown ids are ignored. */
  | { type: 'reorderClips', ids: string[] }
  | { type: 'updateSettings', patch: Partial<MixSettings> }
  | { type: 'setLoudnessCache', loudnessCache: Record<string, LoudnessMeasurement> | undefined }
  /** Several edits applied in order as one undo step (e.g. the changes made in the timeline, or splitting a clip). */
  | { type: 'batch', actions: MixProjectAction[] };

// Optional keys are removed instead of being stored as `undefined`, so saved files and deep comparisons stay clean.
function withoutUndefined<T extends object>(obj: T, keys: (keyof T & string)[]): T {
  return Object.fromEntries(Object.entries(obj).filter(([key, value]) => value !== undefined || !(keys as string[]).includes(key))) as T;
}

const hasChanges = <T extends object>(obj: T, patch: Partial<T>) => (Object.keys(patch) as (keyof T)[]).some((key) => !isEqual(obj[key], patch[key]));

export function mixProjectReducer(project: MixProject, action: MixProjectAction): MixProject {
  switch (action.type) {
    case 'addSources': {
      // The same file can only be a source once
      const existing = new Set(project.sources.map((s) => s.absolutePath));
      const newSources = action.sources.filter((s) => {
        if (existing.has(s.absolutePath) || project.sources.some((s2) => s2.id === s.id)) return false;
        existing.add(s.absolutePath);
        return true;
      });
      if (newSources.length === 0) return project;
      return { ...project, sources: [...project.sources, ...newSources] };
    }

    case 'removeSource': {
      if (!project.sources.some((s) => s.id === action.sourceId)) return project;
      return {
        ...project,
        sources: project.sources.filter((s) => s.id !== action.sourceId),
        clips: project.clips.filter((c) => c.sourceId !== action.sourceId),
      };
    }

    case 'relinkSource': {
      const index = project.sources.findIndex((s) => s.id === action.sourceId);
      const source = project.sources[index];
      if (source == null || !hasChanges(source, action.source)) return project;
      const sources = [...project.sources];
      sources[index] = withoutUndefined({ ...source, ...action.source }, ['width', 'height', 'duration']);
      return { ...project, sources };
    }

    case 'addClip': {
      if (project.clips.some((c) => c.id === action.clip.id)) throw new Error(`Duplicate clip id ${action.clip.id}`);
      const clips = [...project.clips];
      clips.splice(action.index ?? clips.length, 0, action.clip);
      return { ...project, clips };
    }

    case 'updateClip': {
      const index = project.clips.findIndex((c) => c.id === action.clipId);
      const clip = project.clips[index];
      if (clip == null || !hasChanges(clip, action.patch)) return project;
      const clips = [...project.clips];
      clips[index] = withoutUndefined({ ...clip, ...action.patch }, ['minRect']);
      return { ...project, clips };
    }

    case 'removeClip': {
      if (!project.clips.some((c) => c.id === action.clipId)) return project;
      return { ...project, clips: project.clips.filter((c) => c.id !== action.clipId) };
    }

    case 'duplicateClip': {
      const index = project.clips.findIndex((c) => c.id === action.clipId);
      const clip = project.clips[index];
      if (clip == null) return project;
      if (project.clips.some((c) => c.id === action.newId)) throw new Error(`Duplicate clip id ${action.newId}`);
      const clips = [...project.clips];
      clips.splice(index + 1, 0, { ...structuredClone(clip), id: action.newId, name: action.name ?? clip.name });
      return { ...project, clips };
    }

    case 'reorderClips': {
      const byId = new Map(project.clips.map((c) => [c.id, c]));
      const listed = new Set<string>();
      const ordered: MixClip[] = [];
      action.ids.forEach((id) => {
        const clip = byId.get(id);
        if (clip == null || listed.has(id)) return;
        listed.add(id);
        ordered.push(clip);
      });
      const clips = [...ordered, ...project.clips.filter((c) => !listed.has(c.id))];
      if (clips.every((c, i) => c === project.clips[i])) return project;
      return { ...project, clips };
    }

    case 'updateSettings': {
      if (!hasChanges(project.settings, action.patch)) return project;
      return { ...project, settings: withoutUndefined({ ...project.settings, ...action.patch }, ['music']) };
    }

    case 'setLoudnessCache': {
      if (project.loudnessCache === action.loudnessCache) return project;
      return withoutUndefined({ ...project, loudnessCache: action.loudnessCache }, ['loudnessCache']);
    }

    case 'batch': {
      return action.actions.reduce((acc, a) => mixProjectReducer(acc, a), project);
    }

    default: {
      const exhaustive: never = action;
      throw new Error(`Unknown action ${JSON.stringify(exhaustive)}`);
    }
  }
}

/** A new source for a media file. `filePath` must be absolute (it's also the fallback path). */
export function createMixSource({ id, filePath, name }: { id: string, filePath: string, name: string }): MixSource {
  return { id, path: filePath, absolutePath: filePath, name };
}
