import invariant from 'tiny-invariant';

import { getClipRectsAt } from './clipKeyframes';
import { getClipFrame, getRotationFilter, getSourceFrame, getUnrotatedCrop } from './clipRotation';
import { isSquareSar, toCodedRect } from './sampleAspect';
import type { MixClip, MixClipRotation, MixSource, Rect } from './types';

// Clip thumbnails (A2, T31): one JPEG per clip (start frame, cropped to its max rect) shown in ClipList's rows and
// the Mix view's blocks. Generated by main (main/videomix/thumbnails.ts) and cached as files in
// userData/videomix-thumbs/ (hooks/useClipThumbnails.ts). Pure here (cache key + queue), so it's testable in Node;
// the hook wires it to Electron and React.

export const THUMBNAIL_DIR_NAME = 'videomix-thumbs';

/**
 * Cache key of a clip's thumbnail: `sha1(absolutePath + mtime + size + start + maxRect [+ sar])`, hex. Changing the
 * source file, the clip's start or its max rect (dragging the crop) invalidates it — same scheme as loudness.ts's
 * `getLoudnessCacheKey`. Also the cache file's name (without extension), so an existing file is the cache hit.
 * The SAR of an anamorphic source (B1) is part of it, so the thumbnails cropped before T35 (in coded pixels) are
 * regenerated; square pixels leave the keys as they were. Likewise the turn of a clip (E9), only when it has one.
 */
export async function getThumbnailCacheKey({ absolutePath, mtimeMs, size, start, maxRect, sar, rotation = 0 }: {
  absolutePath: string,
  mtimeMs: number,
  size: number,
  start: number,
  maxRect: Rect,
  sar?: MixSource['sar'] | undefined,
  rotation?: MixClipRotation | undefined,
}) {
  const text = [
    absolutePath, mtimeMs, size, start, maxRect.x, maxRect.y, maxRect.width, maxRect.height,
    ...(isSquareSar(sar) ? [] : [`${sar.num}:${sar.den}`]),
    ...(rotation !== 0 ? [`rotation ${rotation}`] : []),
  ].join('\n');
  const digest = await crypto.subtle.digest('SHA-1', new TextEncoder().encode(text));
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

export const getThumbnailFileName = (key: string) => `${key}.jpg`;

/**
 * The max rect a clip's thumbnail shows: the one at the clip's start (A9, T48: an animated framing at that instant,
 * inside the clip's frame). Without keyframes, exactly `clip.maxRect` (so existing thumbnails keep their cache key).
 */
export const getThumbnailMaxRect = (clip: Pick<MixClip, 'start' | 'maxRect' | 'minRect' | 'keyframes' | 'rotation'>, source: Pick<MixSource, 'width' | 'height'> | undefined) => (
  getClipRectsAt(clip, clip.start, getClipFrame(clip, source)).maxRect
);

/**
 * What main's `captureThumbnail` crops for a clip's max rect (display pixels): the same rect for square pixels, or
 * (B1) the rect in coded pixels plus its display aspect ratio, as the render does. E9: for a turned clip (its rect is
 * in the turned frame) the crop is taken in the unturned frame, and `rotation` is the filter that turns it.
 */
export function getThumbnailCrop(maxRect: Rect, source: Pick<MixSource, 'width' | 'height' | 'sar'>, rotation: MixClipRotation = 0): { crop: Rect, aspect?: number | undefined, rotation?: string | undefined } {
  const frame = getSourceFrame(source);
  const unrotated = getUnrotatedCrop(maxRect, frame, rotation);
  const turn = rotation !== 0 ? { rotation: getRotationFilter(rotation) } : {};
  if (isSquareSar(source.sar)) return { crop: unrotated, ...turn };
  return { crop: toCodedRect(unrotated, source.sar, frame), aspect: maxRect.width / maxRect.height, ...turn };
}

/** main/videomix/thumbnails.ts's `captureThumbnail`, via `@electron/remote` (same pattern as loudness.ts/encoders.ts). */
export const captureThumbnail = (params: { filePath: string, timestamp: number, crop: Rect, aspect?: number | undefined, rotation?: string | undefined, outPath: string }): Promise<void> => (
  window.require('@electron/remote').require('./index.js').videomix.captureThumbnail(params)
);

/**
 * Queue of thumbnail generations with limited concurrency: at most `concurrency` run at once, the rest wait their
 * turn. Queuing again under a `key` that's still waiting (not yet started) replaces its task instead of adding a
 * second one — a clip re-queued before its previous request even started (e.g. a fast drag with the debounce still
 * landing back-to-back keys) only ever runs its latest task.
 */
export class ThumbnailQueue {
  private readonly concurrency: number;

  private running = 0;

  private readonly order: string[] = [];

  private readonly tasks = new Map<string, () => Promise<void>>();

  constructor(concurrency: number) {
    invariant(concurrency > 0, 'ThumbnailQueue concurrency must be positive');
    this.concurrency = concurrency;
  }

  enqueue(key: string, task: () => Promise<void>) {
    if (!this.tasks.has(key)) this.order.push(key);
    this.tasks.set(key, task);
    this.drain();
  }

  /** Tasks queued but not yet started. */
  get pendingCount() {
    return this.order.length;
  }

  /** Tasks currently running. */
  get runningCount() {
    return this.running;
  }

  private drain() {
    while (this.running < this.concurrency && this.order.length > 0) {
      const key = this.order.shift()!;
      const task = this.tasks.get(key);
      this.tasks.delete(key);
      // every queued key has a task until it's shifted, so `task` is only missing if this branch is unreachable
      if (task != null) {
        this.running += 1;
        task().finally(() => {
          this.running -= 1;
          this.drain();
        }).catch(() => undefined); // callers report their own errors; the queue only tracks concurrency
      }
    }
  }
}
